name: ${project.name}
version: ${project.version}
description: ${project.description}
author: cnaude
website: ${project.url}
main: com.cnaude.autowhitelist.AutoWhitelist
commands:
  whitelist:
    description: All whitelist commands
    usage: |
      /<command> reload - reloads the whitelist and settings
      /<command> add [player(s)] - adds a player to the whitelist
      /<command> remove [player(s)] - removes a player from the whitelist
      /<command> on|off - actives/deactivates whitelist
      /<command> list - list whitelist entries
      /<command> dblist - list users in database
      /<command> dbdump - dumps users from database to whitelist.txt
      
permissions:
  whitelist.help:
    default: true
    description: Provides admin access to help command
  whitelist.admin:
    default: op
    description: Provides access to all whitelist commands
  whitelist.add:
    default: false
    description: Provides access to add command
  whitelist.reload:
    default: false
    description: Provides access to reloadcommand
  whitelist.reomve:
    default: false
    description: Provides access to reomve command
  whitelist.on:
    default: false
    description: Provides access to on command
  whitelist.off:
    default: false
    description: Provides access to off command
  whitelist.dblist:
    default: false
    description: Provides access to dblist command
  whitelist.dbdump:
    default: false
    description: Provides access to add command