name: Whitelist
main: me.cnaude.plugin.AutoWhitelist.Whitelist
version: 3.1
commands:
  whitelist:
    description: All whitelist commands
    usage: |
      /<command> reload - reloads the whitelist and settings
      /<command> add [player] - adds a player to the whitelist
      /<command> remove [player] - removes a player from the whitelist
      /<command> on|off - actives/deactivates whitelist
      /<command> list - list whitelist entries
      /<command> dblist - list users in database
      
permissions:
  whitelist.admin:
    default: false
    description: Provides admin access to this plugin