name: Whitelist
main: me.cnaude.plugin.AutoWhitelist.WLMain
version: 3.4
commands:
  whitelist:
    description: All whitelist commands
    usage: |
      /<command> reload - reloads the whitelist and settings
      /<command> add [player] - adds a player to the whitelist
      /<command> remove [player] - removes a player from the whitelist
      /<command> on|off - actives/deactivates whitelist
      /<command> list - list whitelist entries
      /<command> dblist - list users in database
      /<command> dbdump - dumps users from database to whitelist.txt
      
permissions:
  whitelist.admin:
    default: false
    description: Provides admin access to this plugin